# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Flowtoolz
email: contact@flowtoolz.com
author: Sebastian Fichtner
description: Flowtoolz is about beautiful tools for creating beautiful things in a beautiful flow.<br>We are in flow building those tools. You are in flow using them,<br>creating your own beautiful things.<br>Focus. Play. Create.
keywords: iOS, macOS, OSX, tvOS, watchOS, app, apps, Swift, Objective-c, software, developer, Sebastian Fichtner, Cocoa, Software Architecture, programmer, mobile, agile, TDD, REST, SCRUM
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://www.flowtoolz.com" # the base hostname & protocol for your site, e.g. http://example.com

header_pages:
  - service/service.md
  - more/more.md
  - about/about.md

paginate: 13

excerpt_separator: <!--more-->

github_username: flowtoolz
facebook_username: SebastianFlowtoolz
linkedin_username: flowtoolz
xing_username: Sebastian_Fichtner5
goodreads_username: flowtoolz
medium_username: flowtoolz

# Build settings
markdown: kramdown
highlighter: rouge
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
